[package]
name = "vocab-search"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
vocab-core = { path = "../vocab-core" }
vocab-dictionary = { path = "../vocab-dictionary" }
vocab-pinyin = { path = "../vocab-pinyin" }

[lints]
workspace = true