[package]
name = "shouci-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "shouci"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
vocab-capture = { path = "../vocab-capture", features = ["clap"] }
vocab-core = { path = "../vocab-core" }
vocab-db = { path = "../vocab-db" }
vocab-dictionary = { path = "../vocab-dictionary" }
vocab-pleco = { path = "../vocab-pleco" }

[lints]
workspace = true
