[package]
name = "vocab-exchange"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rusqlite = { version = "0.40.2", features = ["bundled"] }
vocab-anki = { path = "../vocab-anki" }
vocab-core = { path = "../vocab-core" }
vocab-db = { path = "../vocab-db" }
vocab-dictionary = { path = "../vocab-dictionary" }
vocab-pinyin = { path = "../vocab-pinyin" }
vocab-pleco = { path = "../vocab-pleco" }

[lints]
workspace = true
